production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gsp_production
  pool: 5
  username: root
  password:
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gsp_development
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gsp_test
  pool: 5
  username: root
  password:
  host: localhost
